if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

au BufNewFile,BufRead *.j2 setlocal ft=jinja
au BufNewFile,BufRead *.conf setlocal ft=jinja
au BufNewFile,BufRead *.cfg setlocal ft=jinja

set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

:highlight Comment ctermfg=lightblue
execute pathogen#infect()

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 0
let g:syntastic_check_on_wq = 0
